version: "3.2"

services:
  app:
    container_name: coupon_generator_app
    image: node:10
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 0.0.0.0:3000:3000
    command: npm start